In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [13]:
url='https://raw.githubusercontent.com/girishkuniyal/Predict-housing-prices-in-Portland/master/ex1data2.txt'
df=pd.read_csv(url,header=None)
df.columns=['Size','Bedrooms','Price']
df.head()

Size  Bedrooms   Price
0  2104         3  399900
1  1600         3  329900
2  2400         3  369000
3  1416         2  232000
4  3000         4  539900

In [22]:
X=df[['Size']]
y=df['Price']

In [15]:
poly=PolynomialFeatures(degree=3)
X_poly=poly.fit_transform(X)
X_poly[:5]

array([[1.00000000e+00, 2.10400000e+03, 4.42681600e+06, 9.31402086e+09],
       [1.00000000e+00, 1.60000000e+03, 2.56000000e+06, 4.09600000e+09],
       [1.00000000e+00, 2.40000000e+03, 5.76000000e+06, 1.38240000e+10],
       [1.00000000e+00, 1.41600000e+03, 2.00505600e+06, 2.83915930e+09],
       [1.00000000e+00, 3.00000000e+03, 9.00000000e+06, 2.70000000e+10]])

In [28]:
model=LinearRegression()
model.fit(X_poly,y)

LinearRegression()

In [17]:
model.intercept_

236407.03612922173

In [18]:
model.coef_

array([ 0.00000000e+00, -1.07855433e+02,  1.06190390e-01, -1.38299983e-05])

In [19]:
predict_data=np.array([[3200],[3720]])
predict_data

array([[3200],
       [3720]])

In [26]:
predict_data_poly=poly.transform(predict_data)
predict_data_poly

/Users/miladziekanowska/anaconda3/lib/python3.10/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


array([[1.0000000e+00, 3.2000000e+03, 1.0240000e+07, 3.2768000e+10],
       [1.0000000e+00, 3.7200000e+03, 1.3838400e+07, 5.1478848e+10]])

In [29]:
model.predict(predict_data_poly)

array([525477.8631757, 592737.542783 ])